apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logging.fullname" . }}-config
  labels:
    {{- include "logging.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-route.conf
    @INCLUDE output-s3.conf
    @INCLUDE output-opensearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        Keep_Log            Off
        Annotations         Off
        Labels              On

  filter-route.conf: |
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule          $log "(ERROR|WARN|FATAL|HTTP/1.1 5[0-9][0-9])"  os.logs  false
        Emitter_Name  re_emitted_error

    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule          $log "^.*$"  s3.logs  false
        Emitter_Name  re_emitted_info

  output-opensearch.conf: |
    [OUTPUT]
        Name            es
        Match           os.logs
        Host            {{ .Values.config.opensearch.host }}
        Port            443
        TLS             On
        Index           {{ .Values.config.opensearch.index }}-%Y.%m.%d
        Type            _doc
        AWS_Auth        On
        AWS_Region      {{ .Values.config.opensearch.region }}
        Suppress_Type_Name On

  output-s3.conf: |
    [OUTPUT]
        Name                  s3
        Match                 s3.logs
        bucket                {{ .Values.config.s3.bucket }}
        region                {{ .Values.config.s3.region }}
        compression           gzip
        total_file_size       50M
        upload_timeout        1m
        use_put_object        On
        s3_key_format         /success-logs/%Y/%m/%d/$TAG-%H-%M-%S
        s3_key_format_tag_delimiters .

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
