apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-04-27T16:23"
    spec:
      containers:
      - name: backend
        image: 558231431060.dkr.ecr.ap-northeast-2.amazonaws.com/bookjjeok_cloud_be:8d85410a78e34eee0d363d8fc5c69df6a08a0c54
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 200
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 5
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://10.2.0.225:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_SERVICE_NAME
          value: "backend"
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
