apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookjjeok

resources:
  - backend-deployment.yaml
  - backend-configmap.yaml
  - backend-external-secret.yaml
  - external-secret-store.yaml
  - backend-hpa.yaml
  - backend-service.yaml
  - ingress.yaml
