apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
  namespace: default
  labels:
    app: ai-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: ai-server
        image: 558231431060.dkr.ecr.ap-northeast-2.amazonaws.com/bookjjeok_cloud_ai:dc7eb0c296827e1a926014e8a144fbd500fb4cec
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 10
