apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
  namespace: default
  labels:
    app: ai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
      - name: ai-server
        image: 558231431060.dkr.ecr.ap-northeast-2.amazonaws.com/bookjjeok_cloud_ai:latest
        ports:
        - containerPort: 8000
