replicaCount: 2
image:
  repository: 558231431060.dkr.ecr.ap-northeast-2.amazonaws.com/bookjjeok_cloud_ai
  pullPolicy: IfNotPresent
  tag: "0f7b2f1d15313b3bf6a7d650a14ddacaa6cc7dc1"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ai-server"
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {cpu: 500m, memory: 1Gi}
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
envFromSecret: "backend-secrets"
