apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: logging
  annotations:
    # TODO: S3 및 OpenSearch 쓰기 권한이 있는 IAM Role ARN을 여기에 입력하세요.
    # eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/fluent-bit-role
