{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  {{- if .Values.secretStore.namespace }}
  namespace: {{ .Values.secretStore.namespace }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
{{- end }}
