apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookjjeok-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        # VPC1 Apps
        - name: vpc1-ai
          cluster: vpc1-cluster
          path: charts/ai
          values: values-vpc1.yaml
          namespace: bookjjeok
        - name: vpc1-beck
          cluster: vpc1-cluster
          path: charts/backend
          values: values-vpc1.yaml
          namespace: bookjjeok
        - name: vpc1-logging
          cluster: vpc1-cluster
          path: charts/logging
          values: values.yaml
          namespace: logging
        # VPC2 Apps
        - name: vpc2-ai
          cluster: vpc2-cluster
          path: charts/ai
          values: values-vpc2.yaml
          namespace: bookjjeok
        - name: vpc2-back
          cluster: vpc2-cluster
          path: charts/backend
          values: values-vpc2.yaml
          namespace: bookjjeok
        - name: vpc2-logging
          cluster: vpc2-cluster
          path: charts/logging
          values: values.yaml
          namespace: logging
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ahnwan55/my-app
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          - '{{values}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
