apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpc2-bundle
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: vpc2-ai-helm
          path: charts/ai
          values: values-vpc2.yaml
          namespace: bookjjeok
        - name: vpc2-back-helm
          path: charts/backend
          values: values-vpc2.yaml
          namespace: bookjjeok
        - name: vpc2-logging-helm
          path: charts/logging
          values: values.yaml
          namespace: logging
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ahnwan55/my-app
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          - '{{values}}'
      destination:
        name: vpc2-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
