apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-vpc2
    kind: SecretStore
  target:
    name: backend-secrets # K8s Secret name
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: bookjjeok/vpc2/backend # AWS Secrets Manager Secret name
