apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-vpc2
  namespace: bookjjeok
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      # EC2 Instance Profile 권한 사용
