apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
  namespace: default
  labels:
    app: ai-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
      - name: ai-server
        image: 558231431060.dkr.ecr.ap-northeast-2.amazonaws.com/bookjjeok_cloud_ai:141a3f540137df7af90df0f3f8f1593e21514c56
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: url
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
