spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  sql:
    init:
      mode: never

ai-server:
  url: http://localhost:8000

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

library:
  api-key: ${LIBRARY_API_KEY}