service:
  type: ClusterIP
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: "shared-alb"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
externalSecrets:
  secretStoreRef:
    name: "aws-secretsmanager"
    kind: "ClusterSecretStore"
  secretKey: "bookjjeok/test/backend"
