replicaCount: 2
image:
  repository: 558231431060.dkr.ecr.ap-northeast-2.amazonaws.com/bookjjeok_cloud_be
  pullPolicy: IfNotPresent
  tag: "1343259173d8abd50ef70f345990bc14b91d9652"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "backend"
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: false
config:
  SPRING_PROFILES_ACTIVE: "prod"
  AI_SERVER_URL: "http://ai-server"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://10.2.0.225:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "backend"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_METRICS_EXPORTER: "none"
externalSecrets:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: "aws-secretsmanager"
    kind: "ClusterSecretStore"
  secretKey: "bookjjeok/test/backend"
secretStore:
  enabled: false
cronjob:
  enabled: false
