apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ai-deployment.yaml
  - ai-service.yaml
  - backend-deployment.yaml
  - backend-configmap.yaml
  - backend-external-secret.yaml
  - external-secret-store.yaml
